### ISSUE TITLE
npm start does not start the generated application.

### ISSUE THREAD

**Issue by freakfan15** [asyncapi/nodejs-template#237]
#### Describe the bug
- I was going through the [official docs](https://www.asyncapi.com/docs/tutorials/generate-code) to generate code here.
- npm install and npm start doesn't start the genrerated server inside output dir.

#### How to Reproduce
- used this command `asyncapi generate fromTemplate asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto` to generate the application
- used the asyncapi.yaml file from the streetlight eg in the docs [here](https://www.asyncapi.com/docs/tutorials/create-asyncapi-document)
- when I do `npm start`, the server does not start as mentioned in the docs.
![image](https://github.com/asyncapi/nodejs-template/assets/54408801/e903e7ed-d540-4707-9be8-f6092701c520)

#### Expected behavior
- when i went in the output/src/api/index.js file i didn't see the **init function** being called anywhere. So, I added
`client.init()` and it started as expected.

![image](https://github.com/asyncapi/nodejs-template/assets/54408801/2d9d5686-1f83-4174-8334-1c98ada41982)
![image](https://github.com/asyncapi/nodejs-template/assets/54408801/7dc83de0-a6bc-4e00-af15-4e0d34e4187c)

- I see the client being exported, but according to the docs, just npm start should start the app. That is why raising the issue. Thanks.

**Comment by derberg** [comment]
@freakfan15 hey, you link to https://www.asyncapi.com/docs/tutorials/create-asyncapi-document but it is a document that only explains how to create AsyncAPI document and had nothing to do with this template

Nevertheless I see we have a bug in docs, and also the `npm start` command is in fact not updated because this template no longer generate an app but a library and you should follow https://github.com/asyncapi/nodejs-template?tab=readme-ov-file#adding-custom-code--handlers to actually test how it works

@freakfan15 would you like to contribute needed changes?

**Comment by derberg** [comment]
closing, it is old docs related issue, v3 has different starting commadn `asyncapi new glee --name=tutorial --template tutorial`
